builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .ShortCommit }}"

brews:
  - tap:
      owner: alessiodionisi
      name: homebrew-tap
    description: Spin up Linux VMs with QEMU
    homepage: https://github.com/alessiodionisi/vmkit
    skip_upload: true
    test: |
      system "#{bin}/vmkit -h"
    install: |
      bin.install "vmkit"

release:
  github:
    owner: alessiodionisi
    name: vmkit
  disable: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
