apiVersion: v1beta1
kind: Disk

metadata:
  name: fedora-39-arm64

spec:
  size: 10G

  source:
    url: https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/aarch64/images/Fedora-Cloud-Base-39-1.5.aarch64.qcow2
    checksum:
      algorithm: sha256
      value: 765996d5b77481ca02d0ac06405641bf134ac920cfc1e60d981c64d7971162dc

---
apiVersion: v1beta1
kind: VirtualMachine

metadata:
  name: fedora-39-arm64

spec:
  cpu:
    cpus: 4

  memory:
    size: 4Gi

  disks:
    - name: disk1
      diskRef:
        name: fedora-39-arm64

  networks:
    - {}

  cloudInit:
    userData: |
      #cloud-config

      ssh_authorized_keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILCzqjVP1Yo9clH/8tZa/jP8vK8x7/QvvOmHgRndZV0B me@alessiodionisi.com

    # metaData: |
    #   instance-id: fedora-39-arm64
    #   local-hostname: fedora-39-arm64

    # networkConfig: |
    #   version: 2
    #   ethernets:
    #     interface0:
    #       match:
    #         name: enp*
    #       dhcp4: true
    #       dhcp6: true
