// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VMKitClient is the client API for VMKit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VMKitClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
}

type vMKitClient struct {
	cc grpc.ClientConnInterface
}

func NewVMKitClient(cc grpc.ClientConnInterface) VMKitClient {
	return &vMKitClient{cc}
}

func (c *vMKitClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/VMKit/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vMKitClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, "/VMKit/ListImages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMKitServer is the server API for VMKit service.
// All implementations must embed UnimplementedVMKitServer
// for forward compatibility
type VMKitServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	mustEmbedUnimplementedVMKitServer()
}

// UnimplementedVMKitServer must be embedded to have forward compatible implementations.
type UnimplementedVMKitServer struct {
}

func (UnimplementedVMKitServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedVMKitServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedVMKitServer) mustEmbedUnimplementedVMKitServer() {}

// UnsafeVMKitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMKitServer will
// result in compilation errors.
type UnsafeVMKitServer interface {
	mustEmbedUnimplementedVMKitServer()
}

func RegisterVMKitServer(s grpc.ServiceRegistrar, srv VMKitServer) {
	s.RegisterService(&VMKit_ServiceDesc, srv)
}

func _VMKit_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMKitServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VMKit/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMKitServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VMKit_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMKitServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/VMKit/ListImages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMKitServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VMKit_ServiceDesc is the grpc.ServiceDesc for VMKit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMKit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "VMKit",
	HandlerType: (*VMKitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _VMKit_Create_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _VMKit_ListImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
