// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: virtualmachine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VirtualMachine represents a virtual machine.
type VirtualMachine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *VirtualMachine) Reset() {
	*x = VirtualMachine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualmachine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachine) ProtoMessage() {}

func (x *VirtualMachine) ProtoReflect() protoreflect.Message {
	mi := &file_virtualmachine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachine.ProtoReflect.Descriptor instead.
func (*VirtualMachine) Descriptor() ([]byte, []int) {
	return file_virtualmachine_proto_rawDescGZIP(), []int{0}
}

func (x *VirtualMachine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type VirtualMachineCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vcpus  string   `protobuf:"bytes,2,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	Memory string   `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Image  *string  `protobuf:"bytes,4,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Disks  []string `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
}

func (x *VirtualMachineCreateRequest) Reset() {
	*x = VirtualMachineCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualmachine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachineCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineCreateRequest) ProtoMessage() {}

func (x *VirtualMachineCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virtualmachine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineCreateRequest.ProtoReflect.Descriptor instead.
func (*VirtualMachineCreateRequest) Descriptor() ([]byte, []int) {
	return file_virtualmachine_proto_rawDescGZIP(), []int{1}
}

func (x *VirtualMachineCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualMachineCreateRequest) GetVcpus() string {
	if x != nil {
		return x.Vcpus
	}
	return ""
}

func (x *VirtualMachineCreateRequest) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

func (x *VirtualMachineCreateRequest) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *VirtualMachineCreateRequest) GetDisks() []string {
	if x != nil {
		return x.Disks
	}
	return nil
}

type VirtualMachineCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VirtualMachineCreateResponse) Reset() {
	*x = VirtualMachineCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualmachine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachineCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineCreateResponse) ProtoMessage() {}

func (x *VirtualMachineCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virtualmachine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineCreateResponse.ProtoReflect.Descriptor instead.
func (*VirtualMachineCreateResponse) Descriptor() ([]byte, []int) {
	return file_virtualmachine_proto_rawDescGZIP(), []int{2}
}

type VirtualMachineDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *VirtualMachineDeleteRequest) Reset() {
	*x = VirtualMachineDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualmachine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachineDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineDeleteRequest) ProtoMessage() {}

func (x *VirtualMachineDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virtualmachine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineDeleteRequest.ProtoReflect.Descriptor instead.
func (*VirtualMachineDeleteRequest) Descriptor() ([]byte, []int) {
	return file_virtualmachine_proto_rawDescGZIP(), []int{3}
}

func (x *VirtualMachineDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type VirtualMachineDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VirtualMachineDeleteResponse) Reset() {
	*x = VirtualMachineDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualmachine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachineDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineDeleteResponse) ProtoMessage() {}

func (x *VirtualMachineDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virtualmachine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineDeleteResponse.ProtoReflect.Descriptor instead.
func (*VirtualMachineDeleteResponse) Descriptor() ([]byte, []int) {
	return file_virtualmachine_proto_rawDescGZIP(), []int{4}
}

type VirtualMachineStartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *VirtualMachineStartRequest) Reset() {
	*x = VirtualMachineStartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualmachine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachineStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineStartRequest) ProtoMessage() {}

func (x *VirtualMachineStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virtualmachine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineStartRequest.ProtoReflect.Descriptor instead.
func (*VirtualMachineStartRequest) Descriptor() ([]byte, []int) {
	return file_virtualmachine_proto_rawDescGZIP(), []int{5}
}

func (x *VirtualMachineStartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type VirtualMachineStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VirtualMachineStartResponse) Reset() {
	*x = VirtualMachineStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualmachine_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachineStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineStartResponse) ProtoMessage() {}

func (x *VirtualMachineStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virtualmachine_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineStartResponse.ProtoReflect.Descriptor instead.
func (*VirtualMachineStartResponse) Descriptor() ([]byte, []int) {
	return file_virtualmachine_proto_rawDescGZIP(), []int{6}
}

type VirtualMachineStopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *VirtualMachineStopRequest) Reset() {
	*x = VirtualMachineStopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualmachine_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachineStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineStopRequest) ProtoMessage() {}

func (x *VirtualMachineStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virtualmachine_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineStopRequest.ProtoReflect.Descriptor instead.
func (*VirtualMachineStopRequest) Descriptor() ([]byte, []int) {
	return file_virtualmachine_proto_rawDescGZIP(), []int{7}
}

func (x *VirtualMachineStopRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type VirtualMachineStopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VirtualMachineStopResponse) Reset() {
	*x = VirtualMachineStopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualmachine_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachineStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineStopResponse) ProtoMessage() {}

func (x *VirtualMachineStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virtualmachine_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineStopResponse.ProtoReflect.Descriptor instead.
func (*VirtualMachineStopResponse) Descriptor() ([]byte, []int) {
	return file_virtualmachine_proto_rawDescGZIP(), []int{8}
}

type VirtualMachineListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VirtualMachineListRequest) Reset() {
	*x = VirtualMachineListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualmachine_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachineListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineListRequest) ProtoMessage() {}

func (x *VirtualMachineListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virtualmachine_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineListRequest.ProtoReflect.Descriptor instead.
func (*VirtualMachineListRequest) Descriptor() ([]byte, []int) {
	return file_virtualmachine_proto_rawDescGZIP(), []int{9}
}

type VirtualMachineListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VirtualMachines []*VirtualMachine `protobuf:"bytes,1,rep,name=virtual_machines,json=virtualMachines,proto3" json:"virtual_machines,omitempty"`
}

func (x *VirtualMachineListResponse) Reset() {
	*x = VirtualMachineListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_virtualmachine_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualMachineListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMachineListResponse) ProtoMessage() {}

func (x *VirtualMachineListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virtualmachine_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMachineListResponse.ProtoReflect.Descriptor instead.
func (*VirtualMachineListResponse) Descriptor() ([]byte, []int) {
	return file_virtualmachine_proto_rawDescGZIP(), []int{10}
}

func (x *VirtualMachineListResponse) GetVirtualMachines() []*VirtualMachine {
	if x != nil {
		return x.VirtualMachines
	}
	return nil
}

var File_virtualmachine_proto protoreflect.FileDescriptor

var file_virtualmachine_proto_rawDesc = []byte{
	0x0a, 0x14, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61,
	0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x9a, 0x01, 0x0a,
	0x1b, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x63, 0x70, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x63, 0x70, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x19,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x69, 0x73,
	0x6b, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x64, 0x69, 0x73, 0x6b, 0x73, 0x42,
	0x08, 0x0a, 0x06, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x1e, 0x0a, 0x1c, 0x56, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x31, 0x0a, 0x1b, 0x56, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1e, 0x0a, 0x1c,
	0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x0a, 0x1a,
	0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1d,
	0x0a, 0x1b, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2f, 0x0a,
	0x19, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x53,
	0x74, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1c,
	0x0a, 0x1a, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65,
	0x53, 0x74, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x19,
	0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x58, 0x0a, 0x1a, 0x56, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x10, 0x76, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x52, 0x0f, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x4d, 0x61, 0x63, 0x68, 0x69,
	0x6e, 0x65, 0x73, 0x42, 0x27, 0x5a, 0x25, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x6c, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x64, 0x69, 0x6f, 0x6e, 0x69, 0x73, 0x69,
	0x2f, 0x76, 0x6d, 0x6b, 0x69, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_virtualmachine_proto_rawDescOnce sync.Once
	file_virtualmachine_proto_rawDescData = file_virtualmachine_proto_rawDesc
)

func file_virtualmachine_proto_rawDescGZIP() []byte {
	file_virtualmachine_proto_rawDescOnce.Do(func() {
		file_virtualmachine_proto_rawDescData = protoimpl.X.CompressGZIP(file_virtualmachine_proto_rawDescData)
	})
	return file_virtualmachine_proto_rawDescData
}

var file_virtualmachine_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_virtualmachine_proto_goTypes = []interface{}{
	(*VirtualMachine)(nil),               // 0: VirtualMachine
	(*VirtualMachineCreateRequest)(nil),  // 1: VirtualMachineCreateRequest
	(*VirtualMachineCreateResponse)(nil), // 2: VirtualMachineCreateResponse
	(*VirtualMachineDeleteRequest)(nil),  // 3: VirtualMachineDeleteRequest
	(*VirtualMachineDeleteResponse)(nil), // 4: VirtualMachineDeleteResponse
	(*VirtualMachineStartRequest)(nil),   // 5: VirtualMachineStartRequest
	(*VirtualMachineStartResponse)(nil),  // 6: VirtualMachineStartResponse
	(*VirtualMachineStopRequest)(nil),    // 7: VirtualMachineStopRequest
	(*VirtualMachineStopResponse)(nil),   // 8: VirtualMachineStopResponse
	(*VirtualMachineListRequest)(nil),    // 9: VirtualMachineListRequest
	(*VirtualMachineListResponse)(nil),   // 10: VirtualMachineListResponse
}
var file_virtualmachine_proto_depIdxs = []int32{
	0, // 0: VirtualMachineListResponse.virtual_machines:type_name -> VirtualMachine
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_virtualmachine_proto_init() }
func file_virtualmachine_proto_init() {
	if File_virtualmachine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_virtualmachine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualmachine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachineCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualmachine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachineCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualmachine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachineDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualmachine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachineDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualmachine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachineStartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualmachine_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachineStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualmachine_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachineStopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualmachine_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachineStopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualmachine_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachineListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_virtualmachine_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualMachineListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_virtualmachine_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_virtualmachine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_virtualmachine_proto_goTypes,
		DependencyIndexes: file_virtualmachine_proto_depIdxs,
		MessageInfos:      file_virtualmachine_proto_msgTypes,
	}.Build()
	File_virtualmachine_proto = out.File
	file_virtualmachine_proto_rawDesc = nil
	file_virtualmachine_proto_goTypes = nil
	file_virtualmachine_proto_depIdxs = nil
}
